// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zoI4sidfc7H2SO8ZmHwKIIOQvs24_-4',
    appId: '1:801698897244:web:71f25d1f37cdbb80823599',
    messagingSenderId: '801698897244',
    projectId: 'clean-architecture-212e6',
    authDomain: 'clean-architecture-212e6.firebaseapp.com',
    storageBucket: 'clean-architecture-212e6.appspot.com',
    measurementId: 'G-6L850YWZLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIxyTERO0LGhIx97DfP7SAywxDwqx1-tM',
    appId: '1:801698897244:android:45053835e4fac997823599',
    messagingSenderId: '801698897244',
    projectId: 'clean-architecture-212e6',
    storageBucket: 'clean-architecture-212e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIqSQSKciLJcPuKkE7qwyeGRyauBqdu0g',
    appId: '1:801698897244:ios:3e0315007579446d823599',
    messagingSenderId: '801698897244',
    projectId: 'clean-architecture-212e6',
    storageBucket: 'clean-architecture-212e6.appspot.com',
    iosBundleId: 'com.example.cleanArchitectureFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIqSQSKciLJcPuKkE7qwyeGRyauBqdu0g',
    appId: '1:801698897244:ios:3e0315007579446d823599',
    messagingSenderId: '801698897244',
    projectId: 'clean-architecture-212e6',
    storageBucket: 'clean-architecture-212e6.appspot.com',
    iosBundleId: 'com.example.cleanArchitectureFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zoI4sidfc7H2SO8ZmHwKIIOQvs24_-4',
    appId: '1:801698897244:web:4d09f1c15eeeb7c0823599',
    messagingSenderId: '801698897244',
    projectId: 'clean-architecture-212e6',
    authDomain: 'clean-architecture-212e6.firebaseapp.com',
    storageBucket: 'clean-architecture-212e6.appspot.com',
    measurementId: 'G-B9Q2RNMC9F',
  );

}